/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recipeApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;

class AppTest {
    @Test void testCompleteRecipeDetails() {
        // Ingredient name, unit, price.
        Ingredient newIngredient = new Ingredient("ingName", "ingUnit", 1);
        List<Ingredient> ingredient = Arrays.asList(newIngredient);

        List<String> recipeIngredients = Arrays.asList("1", "centilitre", "IngredientName");
        List<String> recipeInstruction = Arrays.asList("instruction1", "instruction2");
        Recipe recipe = new Recipe("recipeName", 1, "unit", recipeIngredients, ingredient, recipeInstruction);
        
        assertAll("recipeDetails", 
            () -> assertEquals("recipeName", recipe.getRecipeName()),
            () -> assertEquals(1, recipe.getRecipePortion()),
            () -> assertEquals("unit", recipe.getRecipeUnit()),

            () -> assertEquals("ingName", newIngredient.getIngredientName()),
            () -> assertEquals("ingUnit", newIngredient.getIngredientMeasurement()),
            () -> assertEquals(1, newIngredient.getIngredientPrice()),

            () -> assertEquals(1, Integer.parseInt(recipe.getRecipeIngredients().get(0))),
            () -> assertEquals("centilitre", recipe.getRecipeIngredients().get(1)),
            () -> assertEquals("IngredientName", recipe.getRecipeIngredients().get(2)),

            () -> assertEquals("instruction1", recipe.getRecipeInstructions().get(0)),
            () -> assertEquals("instruction2", recipe.getRecipeInstructions().get(1)));
    }

    @Test void testFileReading () {
        FileHandling filehandling = new FileHandling();
        filehandling.setFilePath(System.getProperty("user.dir") + "/src/test/resources/testFile.txt");

        assertEquals("File read sucessfully!", filehandling.readFile());
    }
}
